### ISSUE TITLE
Arduino Library

### ISSUE THREAD

**Issue by SalvoLunar** [pimoroni/lsm303d-python#9]
Hi there,

The product page for this sensor states that it's compatible with Arduino. 
But I cannot find any documentation regarding how to make it work with Arduino.

Would you have any advice?

Thanks,
Salvo

**Comment by helgibbons** [comment]
We don't typically provide Arduino drivers for our products but googling 'LSM303D Arduino library' brings up several promising leads, including links to Polulu and Adafruit libraries for this sensor.

Sounds like you're now sorted from your [forum thread](https://forums.pimoroni.com/t/lsm303d-6dof-motion-sensor-breakout-arduino/21805/), but let us know if you need anything else!
